account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name='account'

urlpatterns = [
	path('profile/<int:user_id>',views.ProfileView,name='account-profile'),
	path('register/',views.register,name='register'),
	path('login/',auth_views.login,name='login'),
	path('logout/',auth_views.logout,name='logout'),
	path('ajax/validateUsername',views.validate_username,name='validate_username'),
	path('ajax/validateEmail',views.validate_email,name='validate_email'),
	path('editprofile/<int:user_id>',views.editProfile,name='edit_user_profile'),
]

post/api/urls.py
from django.urls import path,include
# from .routers import router
from .viewsets import (
	PostListAPIView,
	PostDetailAPIView,
	PostUpdateAPIView,
	PostDestroyAPIView,
	PostCreateAPIView,
	)

app_name='api'

urlpatterns = [
	path('post/',PostListAPIView.as_view(),name='list'),
	path('post/create',PostCreateAPIView.as_view(),name='create'),
	path('post/<pk>',PostDetailAPIView.as_view(),name='detail'),
	path('post/<pk>/update',PostUpdateAPIView.as_view(),name='update'),
	path('post/<pk>/delete',PostDestroyAPIView.as_view(),name='delete'),
]

post/urls.py
from django.urls import path,include
# from .routers import router
from . import views

app_name='post'

urlpatterns = [
	path('',views.IndexView,name='post-home'),
	path('post/create',views.CreateView,name='post-create'),
	path('post/pinned',views.PinnedView,name='post-pinned'),
	path('post/<slug>',views.DetailView,name='post-detail'),
	path('post/<int:post_id>/get_comments',views.GetComment,name='get-comments'),
	path('post/<int:post_id>/update',views.UpdateView,name='post-update'),
	path('post/<int:post_id>/delete',views.DeleteView,name='post-delete'),
	path('post_pin/<int:post_id>',views.PinPost,name='post-pin'),
	path('post/<post_id>/comment',views.PostComment,name='post-comment'),
#	path('api/',include(router.urls)),
	path('api/',include('post.api.urls',namespace="post-api")),
]

third/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('',include('post.urls')),
	path('account/',include('account.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
	urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/models.py
from django.db import models

from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings

from third.utils import unique_slug_generator
from django.db.models.signals import pre_save
from django.dispatch import receiver

class post(models.Model):
	title=models.CharField(max_length=200)
	content=models.TextField(max_length=1000)
	pub_date=models.DateTimeField(default=timezone.now)
	user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,default=1)
	pin=models.BooleanField(default=False)
	image=models.ImageField()
	views=models.IntegerField(default=0)
	slug=models.SlugField(unique=True,max_length=200)

	def __str__(self):
		return self.title + " : " + self.content[:20]

	@property
	def get_comments(self):
		return self.comment_set.all()

	@property
	def comment_count(self):
		count=self.comment_set.all().count()
		return count

@receiver(pre_save,sender=post)
def slug_save(sender,instance, *args, **kwargs):
	if not instance.slug:
		instance.slug=unique_slug_generator(instance,instance.title,instance.slug)

class pinned(models.Model):
	pin_post=models.ForeignKey(post,on_delete=models.CASCADE)
	user=models.ForeignKey(User,on_delete=models.CASCADE)

	def __str__(self):
		return self.pin_post.title + " : " + self.user.username
 
class comment(models.Model):
	post=models.ForeignKey(post,on_delete=models.CASCADE)
	user=models.ForeignKey(User,on_delete=models.CASCADE)
	comment_text=models.CharField(max_length=200)

	def __str__(self):
		return self.user.username + " : " + self.comment_text  

post/forms.py
from django import forms
from .models import post,comment


from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout,HTML,Submit,Field
from crispy_forms.bootstrap import FormActions,PrependedText,Div

class PostForm(forms.ModelForm):

	class Meta:	
		model=post
		fields=['title','content','image']

	def __init__(self,*args,**kwargs):
		super(PostForm,self).__init__(*args,**kwargs)
		self.helper=FormHelper()
		self.fields['title'].label=False
		self.fields['content'].label=False
		self.helper.form_method="POST"
		self.helper.layout=Layout(
			Field('title',placeholder='Blog Title Goes here'),
			Field('content',placeholder='Content Goes here'),
			Field('image'),
			FormActions(
				Submit('save','Create Post',css_class='btn btn-primary'),
				)

			)

class CommentForm(forms.ModelForm):
	class Meta:
		model=comment
		fields=['comment_text']

	def __init__(self,*args,**kwargs):
		super(CommentForm,self).__init__(*args,**kwargs)
		self.helper=FormHelper()
		self.fields['comment_text'].label=False
		self.form_method="POST"
		self.helper.layout=Layout(
			Div(
				Div(PrependedText('comment_text','#',placeholder='Comment Goes here //'),css_class='col-md-10'),
				Div(FormActions(Submit('save','Comment')),css_class='col-md-2')
			,css_class='row'))

post/views.py
from django.shortcuts import render,get_object_or_404
from django.forms.models import model_to_dict

from django.http import HttpResponse,HttpResponseRedirect,Http404,JsonResponse
from django.urls import reverse,reverse_lazy

from django.core import serializers
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger

from django.contrib.auth.decorators import login_required

from .forms import PostForm,CommentForm
from .models import post,pinned,comment
import random
# Create your views here.


def IndexView(request):
	posts=post.objects.order_by('-id')
	recent_posts=post.objects.order_by('-id')[:5]
	most_viewed=post.objects.order_by('-views')[:5]
	has_pinned=False
	paginator=Paginator(posts,4)
	page=request.GET.get('page')
	posts=paginator.get_page(page)
	if(len(posts)!=0):
		rand_post=posts[random.randint(0,len(posts)-1)]
	else:
		rand_post=None
	context={
		'rand_post':rand_post,
		'posts':posts,
		'recents':recent_posts,
		'most_views':most_viewed,
	}
	if(request.user.is_authenticated):
		for p in posts:
			if(request.user.pinned_set.filter(pin_post=p)):
				p.pin=True
				if not(has_pinned):
					has_pinned=True
					latest_pinned=pinned.objects.filter(user=request.user).order_by('-pk')[:1]
					latest_pinned=(latest_pinned[0].pin_post)
					context['latest_pinned']=latest_pinned
	context['has_pinned']=has_pinned
	return render(request,'post/index.html',context)



def DetailView(request,slug):
	selected_post=get_object_or_404(post,slug=slug)
	selected_post.views=selected_post.views + 1
	selected_post.save()
	if selected_post.user == request.user:
		context={
			'post':selected_post,
			'flag':1,
		}
	else:
		context={
			'post':selected_post,
		}
	comments=selected_post.comment_set.all().order_by('-pk')
	context['comments']=comments
	context['form']=CommentForm()
	context['title']='Blog-IT : '+selected_post.title
	return render(request,'post/detail.html',context)



@login_required
def PostComment(request,post_id):
	comment_text=request.GET.get('comment_text',None)
	selected_post=get_object_or_404(post,pk=post_id)
	c=comment(comment_text=comment_text)
	c.post=selected_post
	c.user=request.user
	c.save()
	data={
		'message':'Comment Posted'
	}
	return JsonResponse(data)


def GetComment(request,post_id):
	selected_post=get_object_or_404(post,pk=post_id)
	data_set=[]
	comments=selected_post.comment_set.all().order_by('-pk')
	for i,comment in enumerate(comments):
		username=comment.user.username
		user_id=comment.user.id
		user_pic=comment.user.profile.image.url
		comment_text=comment.comment_text
		data={
			'user_id':user_id,
			'username':username,
			'image':user_pic,
			'comment':comment_text,
		}
		data_set.append(data)
	json_data={
		'comments':data_set
	}
	return JsonResponse(json_data)


@login_required
def CreateView(request):
	if request.POST:
		form=PostForm(request.POST,request.FILES)
	else:
		form=PostForm(None)
	if form.is_valid():
		instance=form.save(commit=False)
		instance.user=request.user
		instance.save()
		return HttpResponseRedirect(reverse_lazy('post:post-detail',kwargs={'slug':instance.slug}))
	context={
		'form':form,
	}
	return render(request,'post/create.html',context)

@login_required
def UpdateView(request,post_id):
	selected_post=get_object_or_404(post,pk=post_id)
	if selected_post.user != request.user:
		raise Http404
	form=PostForm(request.POST or None,instance=selected_post)
	
	if form.is_valid():
		instance=form.save(commit=False)
		instance.save()
		return HttpResponseRedirect(reverse_lazy('post:post-detail',kwargs={'post_id':instance.id}))
	context={
		'title':'Update : '+selected_post.title,
		'post':selected_post,
		'form':form,
	}
	return render(request,'post/update.html',context)

@login_required
def DeleteView(request,post_id):
	selected_post=get_object_or_404(post,pk=post_id)
	if selected_post.user != request.user:
		raise Http404
	context={
		'title':'Confirm deletion : '+selected_post.title,
		'post':selected_post,
	}
	if request.POST:
		selected_post.delete()
		return HttpResponseRedirect(reverse_lazy('post:post-home'))
	return render(request,'post/delete.html',context)

@login_required
def PinPost(request,post_id):
	selected_post=get_object_or_404(post,pk=post_id)
	if(request.user.pinned_set.filter(pin_post=selected_post)):
		query_set=request.user.pinned_set.filter(pin_post=selected_post)[:1]
		instance=query_set[0]
		instance.delete()
		return HttpResponseRedirect(reverse_lazy('post:post-home'))
	instance=pinned(pin_post=selected_post,user=request.user)
	instance.save()
	return HttpResponseRedirect(reverse_lazy('post:post-detail',kwargs={'slug':selected_post.slug}))

@login_required
def PinnedView(request):
	pin_set=request.user.pinned_set.all().order_by('-pk')
	if not(pin_set):
		raise Http404
	pinned_set=[]
	for p in pin_set:
		p.pin=True
		pinned_set.append(p.pin_post)
	context={
		'pinned_posts':pinned_set
	}
	return render(request,'post/pinned.html',context)

post/templates/post/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>
		
		{% if title %}
			{{title}}
		{% else %}
			Blog-IT : Write Everything
		{% endif %}
	</title>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'post/style.css' %}">
</head>
<body>
	<nav class="navbar navbar-expand-sm bg-dark navbar-dark nav_custom">
	  <ul class="navbar-nav">
	    <li class="nav-item active">
	      <a class="nav-link" href="{% url 'post:post-home' %}">Blog-IT : Write Everythin Out</a>
	    </li>
	    {% if user.is_authenticated %}
	    <li class="nav-item float_right">
	     	 <a class="nav-link" href="{% url 'post:post-create' %}">Create Blog</a> 
		</li>
	    <li class="nav-item float_right">
	     	 <a class="nav-link" href="{% url 'account:account-profile' user.id%}">Profile</a> 
		</li>
	    <li class="nav-item ">
	    	<a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
	    </li>

	    {% else %}

	    <li class="nav-item ">
	    	<a class="nav-link" href="{% url 'account:register' %}">Register</a>
	    </li>
	    <li class="nav-item ">
	    	<a class="nav-link" href="{% url 'account:login' %}">Login</a>
	    </li>

	    {% endif %}
	  </ul>
	</nav>

	<div class="jumbotron no_margin">
		<div class="container">
			{% block content %}

			{% endblock content %}
		</div>	
	</div>
 <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script></script>
	

	<!-- Footer Section -->

	<div class="jumbotron footer_custom no_margin">
		<div class="container color_white">
			<div class="row">
				<div class="col-md-4">
					Links:<br>
					<a href="">Pinned Posts</a><br>
					<a href="">Top posts</a><br>
					<a href="">About Us</a><br>
					<a href="">Contact</a><br>
					Mail @ : binish784@hotmail.com<br>

				</div>
				<div class="col-md-4 align_center">
					<br>
					<h2>B-l-o-g--I-T</h2>
					Write and Share<br>
					Blogs
					<br><br>
				</div>
				<div class="col-md-4 color_khaki">
					This is an demo django blog page created on Feb. 3rd, 2019.<br>
					The page is still under development hence some of the features here are not finished. Anyway enjoy the page and hope you like what i created. Any recommendations are Heartly accepted.
				</div>
			</div>
		</div>
	</div>


	{% block Script%}	{% endblock Script%}
	
	

</body>
</html>

post/templates/post/create.html
{% extends 'post/base.html' %}

{% load  crispy_forms_tags %}

{% block content %}



<form action="" method="POST" enctype="multipart/form-data"  style="border-left: 1.5px solid #007bff;padding-left: 20px;">
	{% crispy form %}<br>
</form>

{% endblock content %}

post/templates/post/delete.html
{% extends 'post/base.html' %}

{% block content %}

<form method="POST" action="">
	{% csrf_token%}
	Confirmation for deletion required : <br><br>
		Are you sure you want to delete this post ? <br><br>
	<input type="submit" class="btn btn-danger">
	<a href="{% url 'post:post-home' %}" class="btn btn-primary">Go Home</a>
</form>

{% endblock content %}

post/templates/post/detail.html
{% extends 'post/base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}

{{post.title}} <small><span style='{color:grey;}'> - {{post.user}} </span></small>
{% if flag %}
<span style="font-size: 12px;">
	&nbsp;&nbsp;<a href="{% url 'post:post-update' post.id %}">update</a>
	&nbsp;&nbsp;<a href="{% url 'post:post-delete' post.id %}">delete</a>
	&nbsp;&nbsp;<a href="{% url 'post:post-home' %}">Go Back</a>
</span>
{% endif %}
<br><br><div class="align_center">
<img src="{{post.image.url}}" class="img-fluid">
<br><br></div>
{{post.content}}
<br>

<span class="float_right">
	<small>
		views : {{post.views}}&nbsp;&nbsp;&nbsp;
		comment : {{post.comment_count}}
	</small>
</span>
<br>
<hr>

{% if user.is_authenticated %}
<br>
<form method="GET" action="" id="commentForm" comment_post_url="{% url 'post:post-comment' post.id%}">
	{% crispy form%}
</form>

{% else %}
	<div class="align_center">To add your comment,Please Login First</div>
{% endif%}

<div id='CommentBlock' comment_url="{% url 'post:get-comments' post.id %}"></div>

{% endblock %}


{% block Script %}
<script type="text/javascript" src='{% static "post/ajax.js" %}'></script>

<script type="text/javascript">
	
form=$("#commentForm");
form.submit(function(e){
	e.preventDefault();
	$FormData=form.serialize();
	console.log($FormData);
	$.ajax({
			method:form.attr('method'),
			url:form.attr('comment_post_url'),
			data:$FormData,
			contentType:'application/json',
			dataType:'json',
			success:function(data){
				console.log('comment Has been Posted')
			}
		});
	$('#id_comment_text').val("");
})

comment_block=$('#CommentBlock');

setInterval(function(){
$.ajax({
	method:'GET',
	url:comment_block.attr('comment_url'),
	contentType:'application/json',
	dataType:'json',
	success:function(data){
		console.log(data);
		for(var key in data.comments){
			if(key==0){
				comment_block.html('<img src="'+data.comments[key].image+'" height="40px" width="40px" style="border-radius: 50px;margin-bottom: 5px">&nbsp;&nbsp;');
			}else{
				comment_block.append('<img src="'+data.comments[key].image+'" height="40px" width="40px" style="border-radius: 50px;margin-bottom: 5px">&nbsp;&nbsp;');
			}
			comment_block.append('<span class="comment_username">'+data.comments[key].username+'</span>'+data.comments[key].comment+'<br>');
		};
	}
})

},1000);

</script>


{% endblock %}

post/templates/post/index.html
{% extends 'post/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="row">

	<div class="col-md-7 index-blogPart" >

		<div class="note">
			<div class="container-fluid">
				<div class="row">
					Welcome to Blog-IT, This is an mini project in my journey to learn django. Hope you like it !
				</div>
			</div>
		</div>
		

	{% if latest_pinned %}

	<br><br>
	Pinned Post : <br><br>

	<div class="white_background padding_10">
		<div class="container-fluid">
				<div class="row">
				<div class="col-md-2">
						<img src="{{latest_pinned.user.profile.image.url}}" class="index-profilePic" >
				</div>
				<div class="col-md-10">
					<div class="container-fluid" >
					<div class="row">
						<div class="col-md-8">
							<a href="{% url 'post:post-detail' latest_pinned.slug %}">{{latest_pinned.title|slice:":20"}}</a>
							<small style="color:grey">- {{latest_pinned.user}}</small>
						</div>
					</div>
					</div>
					<img src="{{latest_pinned.image.url}}" height="200px" width=400px" class="align_center padding_10 margin_auto">
					<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					{{latest_pinned.content|slice:":100"}} ...
					<br>
					<a href="" class="color_forest"><small class="float_right">Comments : {{latest_pinned.comment_count}}</small></a>
				</div>
				</div>
				</div>
	</div>
	<a href="{% url 'post:post-pinned' %}"><small class='float_right'>See more </small></a>
	{% endif %}

	<br><br>
		Blog-IT Activities:<br><br>

		{% if posts %}
			{% for post in posts %}
			<p style='color:#007bff'>
				<div class="container-fluid">
				<div class="row  whitesmoke_background padding_10">
				<div class="col-md-2">
						<img src="{{post.user.profile.image.url}}" class="index-profilePic" >
				</div>
				<div class="col-md-10">
					<div class="container-fluid" >
					<div class="row">
						<div class="col-md-8">
							<a href="{% url 'post:post-detail' post.slug %}">{{post.title|slice:":20"}}</a>
							<small style="color:grey">- {{post.user}}</small>
						</div>
						{% if user.is_authenticated %}
						<div class="col-md-2 offset-md-2">
							{% if post.pin %}
								<small><a href="{% url 'post:post-pin' post.id %}">Pinned</a></small>
							{% else %}
								<small><a href="{% url 'post:post-pin' post.id %}">Pin</a></small>
							{% endif %}
						</div>
						{% endif %}
					</div>
					</div>
						<img src="{{post.image.url}}" height="200px" width=400px" class="align_center padding_10 margin_auto"><br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{post.content|slice:":100"}} ...
					<a href="" class="color_forest"><small class="float_right">Comments : {{post.comment_count}}</small></a>
				</div>
				</div>
				</div><br>
			</p>
			{% endfor %}
		{% else %}
			<p style="text-align: center;">Be the first to Post ...</p>
		{% endif %}

<br>
<!--Paginator buttons  	-->

	<div class="container-fluid">
		<div class="row">
			<div class="col-md-8 offset-md-2 padding-10 ">
				<div class="pagination">
					<span class="step-links">
					{% if posts.has_previous %}
						<a href="?page=1" class="btn btn-dark btn-sm margin-5">&laquo; First</a>
						<a href="?page={{posts.previous_page_number}}" class="btn btn-dark btn-sm margin-5">Prev</a>
					{% else %}
						<a href="#" class="btn btn-light btn-sm disabled margin-5">&laquo; First</a>
						<a href="#" class="btn btn-light btn-sm disabled margin-5">Prev</a>
					{% endif %}
					</span>
				
					<span class="current btn btn-light margin-5">
					Page {{posts.number}} of {{posts.paginator.num_pages}}
					</span>
					
					<span class="step-links">
					{% if posts.has_next %}
						<a href="?page={{posts.next_page_number}}" class="btn btn-dark btn-sm margin-5">Next</a>
						<a href="?page={{posts.paginator.num_pages}}" class="btn btn-dark btn-sm margin-5">&raquo; Last</a>
					{% else %}
						<a href="#" class="btn btn-light disabled btn-sm">Next</a>
						<a href="#" class="btn btn-light disabled btn-sm">&raquo; Last</a>
					{% endif %}
					</span>
				</div>	
			</div>
		</div>
	</div>





	</div>
	
	
	<!-- side main page section -->
	<div class="col-md-4 offset-md-1">
		
		
		<!-- Recent Post section -->
		
		<div class="header">
			Recent Posts
		</div>

		{% if recents %}
		{% for recent in recents %}
			<div class="side_link_magenta">
				<a href="{% url 'post:post-detail' recent.slug%}">
					<div style="margin-left: 15px;">{{recent.title}}</div>
				</a>	
			</div>
			<hr>
		{% endfor %}

		{% else %}
		<br>
			No recent Posts
		<br>
		{% endif %}
	<br>
		<!-- Most viewed section -->
		
		<div class="header">
			Most Viewed
		</div>

		{% if most_views %}

		{% for popular in most_views %}
			<div class="side_link_forest">
				<a href="{% url 'post:post-detail' popular.slug %}">
					<div style="margin-left: 15px">{{popular.title}}
					</div>
				</a>
			</div><hr>
		{% endfor %}
		<br>
		{% else %}

		<br>
			No posts yet
		<br>

		{% endif %}

		{% if rand_post %}
		<!-- Random Post section -->

		<div class="header">
			Random Post
		</div>
		<a href="{% url 'post:post-detail' rand_post.slug %}">{{rand_post.title}}<div class="align_center"><br>
			<img src="{{rand_post.image.url}}" height="200px" width="300px">
		</div></a><br>

		{% endif %}

	</div>




</div>



{% endblock content %}

post/templates/post/pinned.html
{% extends 'post/base.html' %}

{% block content %}
{% for post in pinned_posts %}
<p style='color:#007bff'>

	<div class="container">
		<div class="row">
			<div class="col-md-8 offset-md-2">
				<div class="container-fluid">
					<div class="row">
						<div class="col-md-2">
							<img src="{{post.user.profile.image.url}}" class="index-profilePic" >
						</div>
						<div class="col-md-10">
							<div class="container-fluid" >
								<div class="row">
									<div class="col-md-8">
										<a href="{% url 'post:post-detail' post.id %}">{{post.title|slice:":20"}}</a>
										<small style="color:grey">- {{post.user}}</small>
									</div>
									<div class="col-md-2 offset-md-2">
										<small><a href="{% url 'post:post-pin' post.id %}">Pinned</a></small>
									</div>
								</div>
							</div>
							&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{post.content|slice:":100"}} ...
						</div>
					</div>
				</div>		
			</div>
		</div>
	</div>
	<br>
</p>
{% endfor %}

{% endblock content %}

post/templates/post/update.html
{% extends 'post/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

	<form action="" method="POST">
		{% csrf_token %}
		{{form|crispy}}<br>
		<input type="submit" value="Update" class="btn btn-success">
		<a href="{% url 'post:post-detail' post.id %}" class="btn btn-default">Go Back</a>
	</form> 	
{% endblock content %}